config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create]
  resources :cats
  resources :cat_rental_requests, only: [:index, :create, :new, :show, :edit] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  root to: 'cats#index'
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ValidDateValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    if record.changed_attributes[attribute] && record.changed_attributes[attribute] < Date.today
      record.errors.add(attribute, 'cannot be changed')
    elsif value < Date.today
      record.errors.add(attribute, 'cannot be set before today')
    end
  end
end

class CatRentalRequest < ActiveRecord::Base

  STATUSES = %w(PENDING APPROVED DENIED)

  belongs_to :cat

  after_initialize :set_default_status

  validates_presence_of :cat_id, :end_date, :start_date, :status
  validates :cat_id, numericality: { greater_than: 0 }
  validates :status, inclusion: STATUSES
  validates :start_date, :end_date, valid_date: true
  validate :start_not_after_end, :no_overlapping_approved_requests

  def approved?
    self.status == 'APPROVED'
  end

  def denied?
    self.status == 'DENIED'
  end

  def pending?
    self.status == 'PENDING'
  end

  def approve!
    self.status = 'APPROVED'
    save!
  end

  def deny!
    self.status = 'DENIED'
    save!
  end

  private

  def set_default_status
    self.status ||= 'PENDING'
  end

  def overlapping_requests
    CatRentalRequest
      .where('(:id IS NULL) OR (id != :id)', id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
       NOT( (start_date > :end_date) OR (end_date < :start_date) )
    SQL
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def no_overlapping_approved_requests
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] <<
        'Request conflicts with existing approved request'
    end
  end

  def start_not_after_end
    if self.start_date > self.end_date
      errors.add(:start_date, "can't be after end date")
      errors.add(:end_date, "can't be before start date")
    end
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :set_request, except: [:index, :new, :create]
  before_action :not_logged_in?

  def index
    @cat_rental_requests = CatRentalRequest.all
    render json: @cat_rental_requests
  end

  def show
    render :show
  end

  def new
    @cat_rental_request = CatRentalRequest.new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cats_url(current_cat)
    else
      flash.now[:errors] = @cat_rental_request.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @cat_rental_request.update(cat_rental_params)
      redirect_to @cat_rental_request
    else
      flash.now[:errors] = @cat_rental_request.errors.full_messages
      render :edit
    end
  end

  def approve
    @cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def deny
    @cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  private

  def set_request
    @cat_rental_request ||= CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    @cat_rental_request.cat
  end

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :end_date, :start_date, :status)
  end
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/views/cat_rental_requests/_form.html.erb
<form action=<%= @cat_rental_request.persisted? ? cat_rental_request_url(@cat_rental_request) : cat_rental_requests_url %> method='POST'>
  <%= render 'shared/csrf' %>
  <div>
    <label> Select Cat:
      <select name="cat_rental_request[cat_id]">
        <% ([Cat.new(name: 'Select A Cat')] + Cat.all).each do |cat| %>
          <option value=<%= cat.id %> <%= 'selected' if @cat_rental_request.cat_id == cat.id %>>
            <%= cat.name %>
          </option>
        <% end %>
      </select>
    </label>
  </div>
  <br/>

  <div>
    <label>Start Date
      <input type="date" name="cat_rental_request[start_date]" value="<%= @cat_rental_request.start_date %>">
    </label>
  </div>
  <br/>

  <div>
    <label>End Date
      <input type="date" name="cat_rental_request[end_date]" value="<%= @cat_rental_request.end_date %>">
    </label>
  </div>
  <br/>

  <div>
    <input type="submit" name="name" value="<%= action %>">
  </div>
</form>

app/views/cat_rental_requests/edit.html.erb
<h1>Create Rental Request</h1>

<%= render 'form', action: 'Edit' %>
<br/>
<%= link_to 'Back', :back %>

app/views/cat_rental_requests/new.html.erb
<h1>Create Rental Request</h1>

<%= render 'form', action: 'Create' %>
<br/>
<%= link_to 'Back', :back %>