config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create]
  resources :cats
  resources :cat_rental_requests, only: [:index, :create, :new, :show, :edit] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  root to: 'cats#index'
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  birth_date  :date             not null
#  color       :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

require 'action_view'

class Cat < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  COLORS = %w(Black White Orange Calico Grey)

  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :cat_rental_requests, dependent: :destroy

  validates_presence_of :name, :birth_date, :sex, :color, :user_id
  validates :color, inclusion: COLORS
  validates :sex, inclusion: %w(M F)

  def age
    time_ago_in_words(birth_date)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :not_logged_in?
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  before_action :verify_owner, only: [:edit, :update, :destroy]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.owner = current_user

    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def verify_owner
    unless @cat.owner == current_user
      flash[:errors] = ["That's not your cat!!"]
      redirect_to cats_path
    end
  end

  def cat_params
    params.require(:cat)
      .permit(:age, :birth_date, :color, :description, :name, :sex)
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <%= render 'shared/csrf' %>
  <input type="hidden" name="_method" value="<%= method %>">

  <div>
    <label for="cat_name">Name</label><br/>
    <input type="text" id="cat_name" name="cat[name]" value="<%= cat.name %>"/>
  </div>
  <br/>

  <div>
    <label for="cat_birth_date">Birthdate</label><br/>
    <input type="date" id="cat_birth_date" name="cat[birth_date]" value="<%= cat.birth_date %>"/>
  </div>
  <br/>

  <div>
    <label for="cat_color">Color</label><br/>
    <select name="cat[color" id="cat_color">
      <option >Select Color</option>
      <% Cat::COLORS.each do |color| %>
        <option value="<%= color %>" <%= "selected" if cat.color == color %>><%= color %></option>
      <% end %>
    </select>
  </div>
  <br/>

  <div>
    <input type="radio" name="cat[sex]" value="M" id="male" <%= cat.sex == 'M' ? 'checked' : '' %>>
    <label for="male">Male</label>
    <input type="radio" name="cat[sex]" value="F" id="female" <%= cat.sex == 'F' ? 'checked' : '' %>>
    <label for="female">Female</label>
  </div>
  <br/>

  <div>
    <label for="cat_description">Description</label><br/>
    <textarea name="cat[description]" id="cat_description" cols="30" rows="10"><%= cat.description %></textarea>
  </div>

  <div>
    <input type="submit" value="<%= cat.persisted? ? 'Update' : 'Create' %> cat"/>
  </div>
</form>

app/views/cats/_request.html.erb
<tr>
  <td><%= request.start_date %></td>
  <td><%= request.end_date %></td>
  <td>
    <% if request.pending? %>
      <%= button_to 'Approve', approve_cat_rental_request_url(request) %>
      <%= button_to 'Deny', deny_cat_rental_request_url(request) %>
    <% else %>
      <%= request.status %>
    <% end %>
  </td>
</tr>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>
<%= render 'form', cat: @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth date</th>
      <th>Color</th>
      <th>Sex</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= link_to cat.name, cat_url(cat) %></td>
        <td><%= cat.birth_date %></td>
        <td><%= cat.color %></td>
        <td><%= cat.sex %></td>
        <td><%= cat.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>
<%=  link_to 'New Rental Request', new_cat_rental_request_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @cat.name %></h1>

<table>
  <thead>
  <tr>
    <% %w(Age Color Sex Description).each do |attr_name| %>
      <th><%= attr_name %></th>
    <% end %>
  </tr>
  </thead>
  <tr>
    <% [:age, :color, :sex, :description].each do |attr_name| %>
      <td><%= @cat.send(attr_name) %></td>
    <% end %>
  </tr>
</table>
<br/>
<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>
<br/>
<h2>Rental Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
    <%= render 'request', request: request %>
  <% end %>
</table>